test: return code of lint command is managed

diff --git a/linter/js/action.yml b/linter/js/action.yml
--- a/linter/js/action.yml
+++ b/linter/js/action.yml
@@ -22,15 +22,10 @@ runs:
             FILES_JS=$(echo "${{ inputs.ALL_CHANGED_FILES }}" | tr ' ' '\n' | grep -E ".js$" | while read -r FILE; do echo "$GITHUB_WORKSPACE/$FILE"; done | grep $FOLDER | xargs)
             if [ -n "$FILES_JS" ]; then
               echo "Linting files in $FOLDER"
-              cd "$GITHUB_WORKSPACE/$FOLDER" && npm run lint:js:ci -- $FILES_JS
-              EXIT_CODE=$?
-              if [ $EXIT_CODE -ne 0 ]; then
-                echo "Linting failed in $FOLDER"
-              fi
+              cd "$GITHUB_WORKSPACE/$FOLDER" && npm run lint:js:ci -- $FILES_JS || { echo "Linting failed in $FOLDER"; false; }
             else
               echo "No files to lint in $FOLDER"
             fi
           done
         done
         cd "$GITHUB_WORKSPACE"
-        exit $EXIT_CODE
