test: debug exit code

diff --git a/linter/js/action.yml b/linter/js/action.yml
--- a/linter/js/action.yml
+++ b/linter/js/action.yml
@@ -22,7 +22,12 @@ runs:
             FILES_JS=$(echo "${{ inputs.ALL_CHANGED_FILES }}" | tr ' ' '\n' | grep -E ".js$" | while read -r FILE; do echo "$GITHUB_WORKSPACE/$FILE"; done | grep $FOLDER | xargs)
             if [ -n "$FILES_JS" ]; then
               echo "Linting files in $FOLDER"
-              cd "$GITHUB_WORKSPACE/$FOLDER" && npm run lint:js:ci -- $FILES_JS
+              cd "$GITHUB_WORKSPACE/$FOLDER" && npm run lint:js:ci -- $FILES_JS || exit_code=$?
+              echo "Exit code: $exit_code"
+              if [ "$exit_code" -ne 0 ]; then
+                echo "Linting failed for $FILES_JS"
+                exit $exit_code
+              fi
             else
               echo "No files to lint in $FOLDER"
             fi
